# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 510dbbfa0e342af7dca2471e853c450ca87b25483106872b5f3a9f323185d9e16b401b6f330315e192821d1e5eb34fe617da37229826873c52e94854bb54bad5

test:
  secret_key_base: fbc6cf58d6a5851ab8c76d4fce6e385c1ef2d4a1eeb7bf23a4a3cbffcdf534704531a65df4a070e295b58d6684ee664b2659aea8b11d553a3b3b20858d38e0a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
